=== mirkanu/brf2/.astro/collections/conferences.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "legacyPath": {
      "type": "string"
    },
    "datePublished": {
      "type": "string"
    },
    "authors": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "tags": {
      "default": [],
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "rawCategories": {
      "default": [],
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "primaryCategory": {
      "default": null,
      "type": [
        "string",
        "null"
      ]
    },
    "section": {
      "type": "string"
    },
    "year": {
      "type": "integer",
      "minimum": -9007199254740991,
      "maximum": 9007199254740991
    },
    "venue": {
      "default": null,
      "type": [
        "string",
        "null"
      ]
    },
    "subtitle": {
      "default": null,
      "type": [
        "string",
        "null"
      ]
    },
    "theme": {
      "default": null,
      "type": [
        "string",
        "null"
      ]
    },
    "dates": {
      "default": null,
      "type": [
        "string",
        "null"
      ]
    },
    "$schema": {
      "type": "string"
    }
  },
  "required": [
    "title",
    "legacyPath",
    "datePublished",
    "authors",
    "section",
    "year"
  ]
}

=== mirkanu/brf2/src/content/conferences/category-sovereign-grace-galasheils-scotland-1994.json
{
  "title": "\"Sovereign Grace\"",
  "legacyPath": "/conference/category/sovereign-grace-galasheils-scotland-1994",
  "datePublished": "2014-04-26 10:36:19",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [
    "1994"
  ],
  "rawCategories": [
    "lectures"
  ],
  "primaryCategory": "lectures",
  "year": 0,
  "subtitle": "\"Sovereign Grace\"",
  "theme": "\"Sovereign Grace\"",
  "venue": "Galasheils, Scotland, 1994",
  "section": "conference"
}

=== mirkanu/brf2/src/content/conferences/category-the-kingdom-of-god-cefn-lea-wales-2000.json
{
  "title": "\"The Kingdom of God\"",
  "legacyPath": "/conference/category/the-kingdom-of-god-cefn-lea-wales-2000",
  "datePublished": "2014-04-26 10:40:38",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [
    "2000"
  ],
  "rawCategories": [
    "lectures"
  ],
  "primaryCategory": "lectures",
  "year": 0,
  "subtitle": "\"The Kingdom of God\"",
  "theme": "\"The Kingdom of God\"",
  "venue": "Cefn Lea, Wales, 2000",
  "section": "conference"
}

=== mirkanu/brf2/src/content/conferences/category-2016-behold-i-come-quickly-the-reformed-biblical-truth-of-the-end.json
{
  "title": "\"Behold, I Come Quickly: The Reformed, Biblical Truth of the End\"",
  "legacyPath": "/conference/category/2016-behold-i-come-quickly-the-reformed-biblical-truth-of-the-end",
  "datePublished": "2014-09-21 21:54:11",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [
    "2016"
  ],
  "rawCategories": [
    "past"
  ],
  "primaryCategory": "past",
  "year": 2016,
  "subtitle": "\"Behold, I Come Quickly: The Reformed, Biblical Truth of the End\"",
  "theme": "\"Behold, I Come Quickly: The Reformed, Biblical Truth of the End\"",
  "venue": "Castlewellan, Northern Ireland",
  "dates": "16-23 July",
  "section": "conference"
}

=== mirkanu/brf2/src/content/conferences/category-behold-i-come-quickly-the-reformed-biblical-doctrine-of-the-end-castlewellan-castle-2016.json
{
  "title": "\"Behold, I Come Quickly: The Reformed, Biblical Doctrine of the End\"",
  "legacyPath": "/conference/category/behold-i-come-quickly-the-reformed-biblical-doctrine-of-the-end-castlewellan-castle-2016",
  "datePublished": "2017-01-08 16:38:02",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [
    "2016"
  ],
  "rawCategories": [
    "lectures"
  ],
  "primaryCategory": "lectures",
  "year": 0,
  "subtitle": "\"Behold, I Come Quickly: The Reformed, Biblical Doctrine of the End\"",
  "theme": "\"Behold, I Come Quickly: The Reformed, Biblical Doctrine of the End\"",
  "venue": "Castlewellan Castle, 2016",
  "section": "conference"
}
