=== mirkanu/brf2/.astro/collections/journal.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "legacyPath": {
      "type": "string"
    },
    "datePublished": {
      "type": "string"
    },
    "authors": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "tags": {
      "default": [],
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "rawCategories": {
      "default": [],
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "primaryCategory": {
      "default": null,
      "type": [
        "string",
        "null"
      ]
    },
    "section": {
      "type": "string"
    },
    "issueNumber": {
      "default": null,
      "anyOf": [
        {
          "type": "integer",
          "minimum": -9007199254740991,
          "maximum": 9007199254740991
        },
        {
          "type": "null"
        }
      ]
    },
    "issueYear": {
      "default": null,
      "anyOf": [
        {
          "type": "integer",
          "minimum": -9007199254740991,
          "maximum": 9007199254740991
        },
        {
          "type": "null"
        }
      ]
    },
    "pdfLink": {
      "default": null,
      "type": [
        "string",
        "null"
      ]
    },
    "$schema": {
      "type": "string"
    }
  },
  "required": [
    "title",
    "legacyPath",
    "datePublished",
    "authors",
    "section"
  ]
}

=== mirkanu/brf2/src/content/journal/british-reformed-journal-issue-47-summer-2007-editorial-keeping-gods-covenant-a-review-of-keeping-gods-covenant-by-herman-hanko-and-david-engelsma.json
{
  "title": "Editorial Book Review: \"Keeping God’s Covenant\" by Herman Hanko and David Engelsma)",
  "legacyPath": "/journal/articles/british-reformed-journal/issue-47-summer-2007/editorial-keeping-gods-covenant-a-review-of-keeping-gods-covenant-by-herman-hanko-and-david-engelsma",
  "datePublished": "2010-09-12 15:58:43",
  "authors": [
    "MichaelKimmitt"
  ],
  "tags": [
    "book review",
    "editorial",
    "covenant"
  ],
  "rawCategories": [
    "issue-47-summer-2007"
  ],
  "primaryCategory": "issue-47-summer-2007",
  "issueNumber": 47,
  "issueYear": 2007,
  "section": "journal-article"
}

=== mirkanu/brf2/src/content/journal/british-reformed-journal-issue-3-july-september-1993-francis-turretin-institutes-of-elenctic-theology.json
{
  "title": "Book Review: Institutes of Elenctic Theology by Francis Turretin",
  "legacyPath": "/journal/articles/british-reformed-journal/issue-3-july-september-1993/francis-turretin-institutes-of-elenctic-theology",
  "datePublished": "2012-10-30 00:00:06",
  "authors": [
    "H.L.Williams"
  ],
  "tags": [
    "book review"
  ],
  "rawCategories": [
    "issue-03-july-september-1993"
  ],
  "primaryCategory": "issue-03-july-september-1993",
  "issueNumber": 3,
  "issueYear": 1993,
  "section": "journal-article"
}

=== mirkanu/brf2/src/content/journal/category-book-reviews-particular-grace-by-abraham-kuyper-amp-redeem-the-time-by-steve-griffiths.json
{
  "title": "Book Reviews: Particular Grace by Abraham Kuyper &amp; Redeem the Time by Steve Griffiths",
  "legacyPath": "/journal/articles/category/book-reviews-particular-grace-by-abraham-kuyper-amp-redeem-the-time-by-steve-griffiths",
  "datePublished": "2024-09-08 15:06:03",
  "authors": [
    "AllenBaird"
  ],
  "tags": [
    "book review",
    "abraham kuyper",
    "john owen"
  ],
  "rawCategories": [
    "issue-35-autumn-2002"
  ],
  "primaryCategory": "issue-35-autumn-2002",
  "issueNumber": 35,
  "issueYear": 2002,
  "section": "journal-article"
}

=== mirkanu/brf2/src/content/journal/british-reformed-journal-issue-38-summer-2003-giving-the-arminian-babel-a-shake-the-wesley-toplady-controversy-1.json
{
  "title": "Giving the Arminian Babel a Shake: The Wesley-Toplady Controversy (1)",
  "legacyPath": "/journal/articles/british-reformed-journal/issue-38-summer-2003/giving-the-arminian-babel-a-shake-the-wesley-toplady-controversy-1",
  "datePublished": "2010-10-30 00:00:00",
  "authors": [
    "BillLangerak"
  ],
  "tags": [
    "calvinism",
    "arminianism",
    "church history",
    "wesley"
  ],
  "rawCategories": [
    "issue-38-summer-2003"
  ],
  "primaryCategory": "issue-38-summer-2003",
  "issueNumber": 38,
  "issueYear": 2003,
  "section": "journal-article"
}

=== mirkanu/brf2/src/content/journal/british-reformed-journal-issue-21-january-march-1998-a-plea-for-creeds.json
{
  "title": "A Plea for Creeds",
  "legacyPath": "/journal/articles/british-reformed-journal/issue-21-january-march-1998/a-plea-for-creeds",
  "datePublished": "2010-10-30 00:00:00",
  "authors": [
    "RonaldHanko"
  ],
  "tags": [
    "Translated",
    "Polish",
    "German",
    "creeds & confessions"
  ],
  "rawCategories": [
    "issue-21-january-march-1998"
  ],
  "primaryCategory": "issue-21-january-march-1998",
  "issueNumber": 21,
  "issueYear": 1998,
  "section": "journal-article"
}

=== mirkanu/brf2/src/content/journal/category-the-scriptural-presentation-of-gods-hatred.json
{
  "title": "The Scriptural Presentation of God's Hatred",
  "legacyPath": "/journal/articles/category/the-scriptural-presentation-of-gods-hatred",
  "datePublished": "2019-04-23 20:40:59",
  "authors": [
    "HomerC.Hoeksema"
  ],
  "tags": [
    "reprobation",
    "calvinism"
  ],
  "rawCategories": [
    "issue-42-spring-2005"
  ],
  "primaryCategory": "issue-42-spring-2005",
  "issueNumber": 42,
  "issueYear": 2005,
  "section": "journal-article"
}

=== mirkanu/brf2/src/content/journal/british-reformed-journal-issue-09-january-march-1995-the-fight-for-the-reformed-faith.json
{
  "title": "The Fight for the Reformed Faith: DEBATE ON REDEMPTION AT THE WESTMINSTER ASSEMBLY",
  "legacyPath": "/journal/articles/british-reformed-journal/issue-09-january-march-1995/the-fight-for-the-reformed-faith",
  "datePublished": "2010-10-30 00:00:00",
  "authors": [
    "DavidBlunt"
  ],
  "tags": [
    "church history",
    "well-meant offer"
  ],
  "rawCategories": [
    "issue-13-january-march-1996"
  ],
  "primaryCategory": "issue-13-january-march-1996",
  "issueNumber": 13,
  "issueYear": 1996,
  "section": "journal-article"
}

=== mirkanu/brf2/src/content/journal/british-reformed-journal-issue-36-winter-2003-the-development-of-the-doctrine-of-the-covenant-4-augustine-and-sovereign-grace.json
{
  "title": "The Development of the Doctrine of the Covenant (4): Augustine and Sovereign Grace",
  "legacyPath": "/journal/articles/british-reformed-journal/issue-36-winter-2003/the-development-of-the-doctrine-of-the-covenant-4-augustine-and-sovereign-grace",
  "datePublished": "2010-09-12 16:21:31",
  "authors": [
    "AngusStewart"
  ],
  "tags": [
    "Translated",
    "Spanish",
    "church history"
  ],
  "rawCategories": [
    "issue-36-winter-2003"
  ],
  "primaryCategory": "issue-36-winter-2003",
  "issueNumber": 36,
  "issueYear": 2003,
  "section": "journal-article"
}
