=== mirkanu/brf2/.astro/collections/journal.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "legacyPath": {
      "type": "string"
    },
    "datePublished": {
      "type": "string"
    },
    "authors": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "tags": {
      "default": [],
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "rawCategories": {
      "default": [],
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "primaryCategory": {
      "default": null,
      "type": [
        "string",
        "null"
      ]
    },
    "section": {
      "type": "string"
    },
    "issueNumber": {
      "default": null,
      "anyOf": [
        {
          "type": "integer",
          "minimum": -9007199254740991,
          "maximum": 9007199254740991
        },
        {
          "type": "null"
        }
      ]
    },
    "issueYear": {
      "default": null,
      "anyOf": [
        {
          "type": "integer",
          "minimum": -9007199254740991,
          "maximum": 9007199254740991
        },
        {
          "type": "null"
        }
      ]
    },
    "pdfLink": {
      "default": null,
      "type": [
        "string",
        "null"
      ]
    },
    "$schema": {
      "type": "string"
    }
  },
  "required": [
    "title",
    "legacyPath",
    "datePublished",
    "authors",
    "section"
  ]
}

=== mirkanu/brf2/src/content/journal/category-no-private-interpretation-an-old-and-neglected-doctrine-reaffirmed.json
{
  "title": "No Private Interpretation? An Old and Neglected Doctrine Reaffirmed",
  "legacyPath": "/journal/articles/category/no-private-interpretation-an-old-and-neglected-doctrine-reaffirmed",
  "datePublished": "2024-09-08 15:00:48",
  "authors": [
    "AllenBaird"
  ],
  "tags": [],
  "rawCategories": [
    "issue-35-autumn-2002"
  ],
  "primaryCategory": "issue-35-autumn-2002",
  "issueNumber": 35,
  "issueYear": 2002,
  "section": "journal-article"
}

=== mirkanu/brf2/src/content/journal/category-the-erosion-of-biblical-psalmody-in-scots-presbyterianism.json
{
  "title": "The Decline of Reformation Calvinism in 19th Cent. Scotland Part Five The Erosion of Biblical Psalmody in Scots Presbyterianism",
  "legacyPath": "/journal/articles/category/the-erosion-of-biblical-psalmody-in-scots-presbyterianism",
  "datePublished": "2019-04-18 22:36:56",
  "authors": [
    "H.L.Williams"
  ],
  "tags": [
    "church history",
    "exclusive psalmody"
  ],
  "rawCategories": [
    "issue-27-july-september-1999"
  ],
  "primaryCategory": "issue-27-july-september-1999",
  "issueNumber": 27,
  "issueYear": 1999,
  "section": "journal-article"
}

=== mirkanu/brf2/src/content/journal/category-be-ye-holy-2g2e3.json
{
  "title": "Behold, I Come Quickly",
  "legacyPath": "/literature/category/be-ye-holy-2g2e3",
  "datePublished": "2018-08-27 05:07:39",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [
    "David J. Engelsma",
    "Andrew Lanning"
  ],
  "rawCategories": [
    "book"
  ],
  "primaryCategory": "book",
  "issueNumber": null,
  "issueYear": null,
  "section": "journal-article"
}

=== mirkanu/brf2/src/content/journal/articles-category-anatomy-of-a-revival-5.json
{
  "title": "Anatomy of a Revival (5)",
  "legacyPath": "/journal/articles/articles/category/anatomy-of-a-revival-5",
  "datePublished": "2019-04-23 21:13:04",
  "authors": [
    "H.L.Williams"
  ],
  "tags": [
    "revivals"
  ],
  "rawCategories": [
    "issue-44-winter-2005"
  ],
  "primaryCategory": "issue-44-winter-2005",
  "issueNumber": 44,
  "issueYear": 2005,
  "section": "journal-article"
}

=== mirkanu/brf2/src/content/journal/category-edited-half-away.json
{
  "title": "Edited Half Away",
  "legacyPath": "/journal/articles/category/edited-half-away",
  "datePublished": "2019-04-18 18:13:30",
  "authors": [
    "RonaldHanko"
  ],
  "tags": [],
  "rawCategories": [
    "issue-25-january-march-1999"
  ],
  "primaryCategory": "issue-25-january-march-1999",
  "issueNumber": 25,
  "issueYear": 1999,
  "section": "journal-article"
}

=== mirkanu/brf2/src/content/journal/british-reformed-journal-issue-29-january-march-2000-the-meaning-of-baptism-with-special-reference-to-the-baptist-view-1.json
{
  "title": "The Meaning of Baptism with Special Reference to the Baptist View (1)",
  "legacyPath": "/journal/articles/british-reformed-journal/issue-29-january-march-2000/the-meaning-of-baptism-with-special-reference-to-the-baptist-view-1",
  "datePublished": "2010-10-30 00:00:00",
  "authors": [
    "AngusStewart"
  ],
  "tags": [
    "Translated",
    "Italian",
    "baptism"
  ],
  "rawCategories": [
    "issue-29-january-march-2000"
  ],
  "primaryCategory": "issue-29-january-march-2000",
  "issueNumber": 29,
  "issueYear": 2000,
  "section": "journal-article"
}

=== mirkanu/brf2/src/content/journal/articles-category-house-churchism-an-ecclesiastical-panacea-or-poison-2.json
{
  "title": "House-Churchism: An Ecclesiastical Panacea or Poison? (2)",
  "legacyPath": "/journal/articles/articles/category/house-churchism-an-ecclesiastical-panacea-or-poison-2",
  "datePublished": "2020-05-31 21:08:43",
  "authors": [
    "SamuelWatterson"
  ],
  "tags": [
    "ecclesiology"
  ],
  "rawCategories": [
    "issue-70-win-2019-2020"
  ],
  "primaryCategory": "issue-70-win-2019-2020",
  "issueNumber": 70,
  "issueYear": 2019,
  "section": "journal-article"
}

=== mirkanu/brf2/src/content/journal/category-of-communion-with-god-the-father-son-and-holy-ghost-2.json
{
  "title": "Of communion With God the Father, Son and Holy Ghost (2)",
  "legacyPath": "/journal/articles/category/of-communion-with-god-the-father-son-and-holy-ghost-2",
  "datePublished": "2017-07-16 20:14:10",
  "authors": [
    "JohnOwen"
  ],
  "tags": [
    "trinity",
    "christian living"
  ],
  "rawCategories": [
    "issue-63"
  ],
  "primaryCategory": "issue-63",
  "issueNumber": 63,
  "issueYear": null,
  "section": "journal-article"
}
