=== mirkanu/brf2/.astro/collections/journal.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "legacyPath": {
      "type": "string"
    },
    "datePublished": {
      "type": "string"
    },
    "authors": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "tags": {
      "default": [],
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "rawCategories": {
      "default": [],
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "primaryCategory": {
      "default": null,
      "type": [
        "string",
        "null"
      ]
    },
    "section": {
      "type": "string"
    },
    "issueNumber": {
      "default": null,
      "anyOf": [
        {
          "type": "integer",
          "minimum": -9007199254740991,
          "maximum": 9007199254740991
        },
        {
          "type": "null"
        }
      ]
    },
    "issueYear": {
      "default": null,
      "anyOf": [
        {
          "type": "integer",
          "minimum": -9007199254740991,
          "maximum": 9007199254740991
        },
        {
          "type": "null"
        }
      ]
    },
    "pdfLink": {
      "default": null,
      "type": [
        "string",
        "null"
      ]
    },
    "$schema": {
      "type": "string"
    }
  },
  "required": [
    "title",
    "legacyPath",
    "datePublished",
    "authors",
    "section"
  ]
}

=== mirkanu/brf2/src/content/journal/british-reformed-journal-issue-48-winter-2008-the-1000-years-of-revelation-20-1.json
{
  "title": "The 1,000 Years of Revelation 20 (1)",
  "legacyPath": "/journal/articles/british-reformed-journal/issue-48-winter-2008/the-1000-years-of-revelation-20-1",
  "datePublished": "2010-08-04 12:25:37",
  "authors": [
    "AngusStewart"
  ],
  "tags": [
    "Translated",
    "Polish",
    "eschatology"
  ],
  "rawCategories": [
    "issue-48-winter-2008"
  ],
  "primaryCategory": "issue-48-winter-2008",
  "issueNumber": 48,
  "issueYear": 2008,
  "section": "journal-article"
}

=== mirkanu/brf2/src/content/journal/british-reformed-journal-issue-44-winter-2005-the-free-offer-issue-1.json
{
  "title": "The Free Offer Issue (1)",
  "legacyPath": "/journal/articles/british-reformed-journal/issue-44-winter-2005/the-free-offer-issue-1",
  "datePublished": "2010-09-12 16:21:31",
  "authors": [
    "H.L.Williams"
  ],
  "tags": [
    "well-meant offer",
    "calvinism"
  ],
  "rawCategories": [
    "issue-44-winter-2005"
  ],
  "primaryCategory": "issue-44-winter-2005",
  "issueNumber": 44,
  "issueYear": 2005,
  "section": "journal-article"
}

=== mirkanu/brf2/src/content/journal/books-a-pamphlets-books-the-reformed-worldview.json
{
  "title": "The Reformed Worldview",
  "legacyPath": "/literature/books-a-pamphlets/books/the-reformed-worldview",
  "datePublished": "2012-09-17 00:00:00",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [
    "Herman Hanko",
    "David J. Engelsma"
  ],
  "rawCategories": [
    "book"
  ],
  "primaryCategory": "book",
  "issueNumber": null,
  "issueYear": null,
  "section": "journal-article"
}

=== mirkanu/brf2/src/content/journal/british-reformed-journal-issue-3-july-september-1993-robust-christianity.json
{
  "title": "Robust Christianity",
  "legacyPath": "/journal/articles/british-reformed-journal/issue-3-july-september-1993/robust-christianity",
  "datePublished": "2012-10-30 00:00:04",
  "authors": [
    "J.C.Ryle"
  ],
  "tags": [],
  "rawCategories": [
    "issue-03-july-september-1993"
  ],
  "primaryCategory": "issue-03-july-september-1993",
  "issueNumber": 3,
  "issueYear": 1993,
  "section": "journal-article"
}

=== mirkanu/brf2/src/content/journal/category-the-reformed-family-authoritative-content-of-the-gospel-rhnp4-hx2r6.json
{
  "title": "A Report on the 2022 BRF Conference",
  "legacyPath": "/journal/articles/category/the-reformed-family-authoritative-content-of-the-gospel-rhnp4-hx2r6",
  "datePublished": "2023-10-08 09:02:46",
  "authors": [
    "BrianHarris"
  ],
  "tags": [
    "brf conference review"
  ],
  "rawCategories": [
    "issue-74-summer-2022"
  ],
  "primaryCategory": "issue-74-summer-2022",
  "issueNumber": 74,
  "issueYear": 2022,
  "section": "journal-article"
}

=== mirkanu/brf2/src/content/journal/books-a-pamphlets-books-the-five-points-of-calvinism.json
{
  "title": "The Five Points of Calvinism",
  "legacyPath": "/literature/books-a-pamphlets/books/the-five-points-of-calvinism",
  "datePublished": "2010-07-24 16:57:57",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [
    "Herman Hanko",
    "David J. Engelsma"
  ],
  "rawCategories": [
    "book"
  ],
  "primaryCategory": "book",
  "issueNumber": null,
  "issueYear": null,
  "section": "journal-article"
}

=== mirkanu/brf2/src/content/journal/category-the-reformed-life-and-world-view-what-is-it.json
{
  "title": "The Reformed Life and World View - What is it?",
  "legacyPath": "/journal/articles/category/the-reformed-life-and-world-view-what-is-it",
  "datePublished": "2014-08-24 20:46:08",
  "authors": [
    "WFSpanner"
  ],
  "tags": [],
  "rawCategories": [
    "issue-04"
  ],
  "primaryCategory": "issue-04",
  "issueNumber": 4,
  "issueYear": null,
  "section": "journal-article"
}

=== mirkanu/brf2/src/content/journal/category-75ea3ze4uwp76f9e2zbfku3puzb4j9.json
{
  "title": "Does God Love Everyone? (1)",
  "legacyPath": "/journal/articles/category/75ea3ze4uwp76f9e2zbfku3puzb4j9",
  "datePublished": "2016-03-20 15:51:54",
  "authors": [
    "PaulFahy"
  ],
  "tags": [
    "well-meant offer"
  ],
  "rawCategories": [
    "issue-15"
  ],
  "primaryCategory": "issue-15",
  "issueNumber": 15,
  "issueYear": null,
  "section": "journal-article"
}
