=== mirkanu/brf2/.astro/collections/pages.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "legacyPath": {
      "type": "string"
    },
    "datePublished": {
      "type": "string"
    },
    "authors": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "tags": {
      "default": [],
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "rawCategories": {
      "default": [],
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "primaryCategory": {
      "default": null,
      "type": [
        "string",
        "null"
      ]
    },
    "section": {
      "type": "string"
    },
    "$schema": {
      "type": "string"
    }
  },
  "required": [
    "title",
    "legacyPath",
    "datePublished",
    "authors",
    "section"
  ]
}

=== mirkanu/brf2/src/content/podcasts/category-20042-keeping-gods-covenant-in-the-church.json
{
  "title": "2004:2 Keeping God's Covenant in the Church",
  "legacyPath": "/podcast/category/20042-keeping-gods-covenant-in-the-church",
  "datePublished": "2024-08-25 16:14:26",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [],
  "rawCategories": [
    "2004"
  ],
  "primaryCategory": "2004",
  "section": "podcast"
}

=== mirkanu/brf2/src/content/podcasts/category-20004-the-kingdom-gospel-and-law.json
{
  "title": "2000:4 The Kingdom, Gospel and Law",
  "legacyPath": "/podcast/category/20004-the-kingdom-gospel-and-law",
  "datePublished": "2024-08-25 16:01:44",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [],
  "rawCategories": [
    "2000"
  ],
  "primaryCategory": "2000",
  "section": "podcast"
}

=== mirkanu/brf2/src/content/podcasts/category-2014-lords-day-sermon-only-the-holy-shall-inherit-the-kingdom.json
{
  "title": "2014 Lord's Day Sermon: Only the Holy Shall Inherit the Kingdom",
  "legacyPath": "/podcast/category/2014-lords-day-sermon-only-the-holy-shall-inherit-the-kingdom",
  "datePublished": "2024-08-25 21:20:33",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [],
  "rawCategories": [
    "2014"
  ],
  "primaryCategory": "2014",
  "section": "podcast"
}

=== mirkanu/brf2/src/content/podcasts/category-4-the-holy-spirit-as-the-spirit-of-truth.json
{
  "title": "4  The Holy Spirit as the Spirit of Truth",
  "legacyPath": "/podcast/category/4-the-holy-spirit-as-the-spirit-of-truth",
  "datePublished": "2024-08-25 20:43:06",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [],
  "rawCategories": [
    "2008"
  ],
  "primaryCategory": "2008",
  "section": "podcast"
}

=== mirkanu/brf2/src/content/podcasts/category-2014-lords-day-sermon-the-calling-to-work-out-our-own-salvation.json
{
  "title": "2014 Lord's Day Sermon: The Calling to Work Out Our Own Salvation",
  "legacyPath": "/podcast/category/2014-lords-day-sermon-the-calling-to-work-out-our-own-salvation",
  "datePublished": "2024-08-25 21:19:37",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [],
  "rawCategories": [
    "2014"
  ],
  "primaryCategory": "2014",
  "section": "podcast"
}

=== mirkanu/brf2/src/content/podcasts/category-20045-keeping-gods-covenant-and-the-exercise-of-discipline.json
{
  "title": "2004:5 Keeping God's Covenant and the Exercise of Discipline",
  "legacyPath": "/podcast/category/20045-keeping-gods-covenant-and-the-exercise-of-discipline",
  "datePublished": "2024-08-25 16:16:35",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [],
  "rawCategories": [
    "2004"
  ],
  "primaryCategory": "2004",
  "section": "podcast"
}

=== mirkanu/brf2/src/content/podcasts/category-20046-keeping-gods-covenant-and-the-antithetical-life.json
{
  "title": "2004:6 Keeping God's Covenant and the Antithetical Life",
  "legacyPath": "/podcast/category/20046-keeping-gods-covenant-and-the-antithetical-life",
  "datePublished": "2024-08-25 16:17:14",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [],
  "rawCategories": [
    "2004"
  ],
  "primaryCategory": "2004",
  "section": "podcast"
}

=== mirkanu/brf2/src/content/podcasts/category-20082-the-outpouring-of-the-holy-spirit.json
{
  "title": "2008:2  The Outpouring of the Holy Spirit",
  "legacyPath": "/podcast/category/20082-the-outpouring-of-the-holy-spirit",
  "datePublished": "2024-08-25 19:54:54",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [],
  "rawCategories": [
    "2008"
  ],
  "primaryCategory": "2008",
  "section": "podcast"
}
