=== mirkanu/brf2/.astro/collections/pages.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "legacyPath": {
      "type": "string"
    },
    "datePublished": {
      "type": "string"
    },
    "authors": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "tags": {
      "default": [],
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "rawCategories": {
      "default": [],
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "primaryCategory": {
      "default": null,
      "type": [
        "string",
        "null"
      ]
    },
    "section": {
      "type": "string"
    },
    "$schema": {
      "type": "string"
    }
  },
  "required": [
    "title",
    "legacyPath",
    "datePublished",
    "authors",
    "section"
  ]
}

=== mirkanu/brf2/src/content/podcasts/category-19963-the-church-its-nature.json
{
  "title": "1996:3 The Church: Its Nature",
  "legacyPath": "/podcast/category/19963-the-church-its-nature",
  "datePublished": "2024-08-25 15:43:54",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [],
  "rawCategories": [
    "1996"
  ],
  "primaryCategory": "1996",
  "section": "podcast"
}

=== mirkanu/brf2/src/content/podcasts/category-19926-the-covenant-as-a-pattern-for-marriage.json
{
  "title": "1992:6 The Covenant as a Pattern for Marriage",
  "legacyPath": "/podcast/category/19926-the-covenant-as-a-pattern-for-marriage",
  "datePublished": "2024-08-25 15:28:40",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [],
  "rawCategories": [],
  "primaryCategory": null,
  "section": "podcast"
}

=== mirkanu/brf2/src/content/podcasts/category-20122-the-content-of-the-witness.json
{
  "title": "2012:2 The Content of the Witness",
  "legacyPath": "/podcast/category/20122-the-content-of-the-witness",
  "datePublished": "2024-08-25 21:04:49",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [],
  "rawCategories": [
    "2012"
  ],
  "primaryCategory": "2012",
  "section": "podcast"
}

=== mirkanu/brf2/src/content/podcasts/category-19962-the-church-gathered-by-the-gospel.json
{
  "title": "1996:2 The Church: Gathered by the Gospel",
  "legacyPath": "/podcast/category/19962-the-church-gathered-by-the-gospel",
  "datePublished": "2024-08-25 15:42:59",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [],
  "rawCategories": [
    "1996"
  ],
  "primaryCategory": "1996",
  "section": "podcast"
}

=== mirkanu/brf2/src/content/podcasts/category-2012-lords-day-sermon-by-the-spirit-of-the-lord.json
{
  "title": "2012 Lord's Day Sermon: By the Spirit of the Lord",
  "legacyPath": "/podcast/category/2012-lords-day-sermon-by-the-spirit-of-the-lord",
  "datePublished": "2024-08-25 21:01:26",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [],
  "rawCategories": [
    "2012"
  ],
  "primaryCategory": "2012",
  "section": "podcast"
}

=== mirkanu/brf2/src/content/podcasts/category-20066-preservation-of-the-saints.json
{
  "title": "2006:6 Preservation of the Saints",
  "legacyPath": "/podcast/category/20066-preservation-of-the-saints",
  "datePublished": "2024-08-25 16:23:15",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [],
  "rawCategories": [
    "2006"
  ],
  "primaryCategory": "2006",
  "section": "podcast"
}

=== mirkanu/brf2/src/content/podcasts/category-6-the-holy-spirit-and-the-church.json
{
  "title": "6  The Holy Spirit and the Church",
  "legacyPath": "/podcast/category/6-the-holy-spirit-and-the-church",
  "datePublished": "2024-08-25 20:45:31",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [],
  "rawCategories": [
    "2008"
  ],
  "primaryCategory": "2008",
  "section": "podcast"
}

=== mirkanu/brf2/src/content/podcasts/category-20124-the-personal-witness-by-the-word.json
{
  "title": "2012:4 The Personal Witness by the Word",
  "legacyPath": "/podcast/category/20124-the-personal-witness-by-the-word",
  "datePublished": "2024-08-25 21:06:57",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [],
  "rawCategories": [
    "2012"
  ],
  "primaryCategory": "2012",
  "section": "podcast"
}
