=== mirkanu/brf2/.astro/collections/pages.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "legacyPath": {
      "type": "string"
    },
    "datePublished": {
      "type": "string"
    },
    "authors": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "tags": {
      "default": [],
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "rawCategories": {
      "default": [],
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "primaryCategory": {
      "default": null,
      "type": [
        "string",
        "null"
      ]
    },
    "section": {
      "type": "string"
    },
    "$schema": {
      "type": "string"
    }
  },
  "required": [
    "title",
    "legacyPath",
    "datePublished",
    "authors",
    "section"
  ]
}

=== mirkanu/brf2/src/content/podcasts/category-3-the-holy-spirit-and-the-covenant-of-grace.json
{
  "title": "3  The Holy Spirit and the Covenant of Grace",
  "legacyPath": "/podcast/category/3-the-holy-spirit-and-the-covenant-of-grace",
  "datePublished": "2024-08-25 20:42:12",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [],
  "rawCategories": [
    "2008"
  ],
  "primaryCategory": "2008",
  "section": "podcast"
}

=== mirkanu/brf2/src/content/podcasts/category-20005-the-kingdom-and-civil-government.json
{
  "title": "2000:5 The Kingdom and Civil Government",
  "legacyPath": "/podcast/category/20005-the-kingdom-and-civil-government",
  "datePublished": "2024-08-25 16:02:25",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [],
  "rawCategories": [
    "2000"
  ],
  "primaryCategory": "2000",
  "section": "podcast"
}

=== mirkanu/brf2/src/content/podcasts/category-19924-the-covenant-children-of-abraham.json
{
  "title": "1992:4 The Covenant Children of Abraham",
  "legacyPath": "/podcast/category/19924-the-covenant-children-of-abraham",
  "datePublished": "2024-08-25 15:21:57",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [],
  "rawCategories": [],
  "primaryCategory": null,
  "section": "podcast"
}

=== mirkanu/brf2/src/content/podcasts/category-19942-sovereign-grace-and-the-cross-of-christ.json
{
  "title": "1994:2 Sovereign Grace and The Cross of Christ",
  "legacyPath": "/podcast/category/19942-sovereign-grace-and-the-cross-of-christ",
  "datePublished": "2024-08-25 15:34:36",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [],
  "rawCategories": [],
  "primaryCategory": null,
  "section": "podcast"
}

=== mirkanu/brf2/src/content/podcasts/category-20061-the-history-of-calvinism.json
{
  "title": "2006:1 The History of Calvinism",
  "legacyPath": "/podcast/category/20061-the-history-of-calvinism",
  "datePublished": "2024-08-25 16:18:35",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [],
  "rawCategories": [
    "2006"
  ],
  "primaryCategory": "2006",
  "section": "podcast"
}

=== mirkanu/brf2/src/content/podcasts/category-4-the-reformed-believer-and-money.json
{
  "title": "4  The Reformed Believer and Money",
  "legacyPath": "/podcast/category/4-the-reformed-believer-and-money",
  "datePublished": "2024-08-25 20:54:34",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [],
  "rawCategories": [
    "2010"
  ],
  "primaryCategory": "2010",
  "section": "podcast"
}

=== mirkanu/brf2/src/content/podcasts/category-7-special-lecture-on-charismaticism.json
{
  "title": "7  Special Lecture on Charismaticism",
  "legacyPath": "/podcast/category/7-special-lecture-on-charismaticism",
  "datePublished": "2024-08-25 20:46:36",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [],
  "rawCategories": [
    "2008"
  ],
  "primaryCategory": "2008",
  "section": "podcast"
}

=== mirkanu/brf2/src/content/podcasts/category-2014-introduction-zealous-of-good-works.json
{
  "title": "2014 Introduction: Zealous of Good Works",
  "legacyPath": "/podcast/category/2014-introduction-zealous-of-good-works",
  "datePublished": "2024-08-25 21:12:43",
  "authors": [
    "manuelkuhs@gmail.com"
  ],
  "tags": [],
  "rawCategories": [
    "2014"
  ],
  "primaryCategory": "2014",
  "section": "podcast"
}
